/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

import gradle.java.domain.OnlineShop;

public class App {
    public static void main(String[] args) {
        OnlineShop onlineShop = new OnlineShop();
        onlineShop.showProducts();
    }
}
